name: Release
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']
    paths-ignore: [ 'docs/**' ]

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    environment: nuget
    steps:
    - uses: actions/checkout@v3
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Install dotnet workload
      run: dotnet workload install maui
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -p:Version="${env:MAJOR}.${env:MINOR}.${env:PATCH}" --no-restore --configuration Release
    # - name: Test
    #  run: dotnet test -p:Version="${env:MAJOR}.${env:MINOR}.${env:PATCH}" --no-build --configuration Release
    - name: Pack
      run: dotnet pack -p:Version="${env:MAJOR}.${env:MINOR}.${env:PATCH}" --configuration Release --output nupkgs
    - name: Push
      run: dotnet nuget push "nupkgs\*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate